# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c_s_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='c_s_message.proto',
  package='console_server_message',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11\x63_s_message.proto\x12\x16\x63onsole_server_message\"e\n\rtotal_message\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\x0b\n\x03key\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\r\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x0c\n\x04\x66lag\x18\x06 \x01(\t\"%\n\x06r7_msg\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\r\n\x05\x63ount\x18\x02 \x02(\r\"%\n\x06r4_msg\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\t\"\x16\n\x06r5_msg\x12\x0c\n\x04type\x18\x01 \x02(\r\"%\n\x06r8_msg\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\r\n\x05\x65rror\x18\x02 \x02(\t\"\"\n\x04\x66lag\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\x0c\n\x04\x66lag\x18\x02 \x02(\t'
)




_TOTAL_MESSAGE = _descriptor.Descriptor(
  name='total_message',
  full_name='console_server_message.total_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='console_server_message.total_message.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='console_server_message.total_message.key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='console_server_message.total_message.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='console_server_message.total_message.count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='console_server_message.total_message.error', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='console_server_message.total_message.flag', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=146,
)


_R7_MSG = _descriptor.Descriptor(
  name='r7_msg',
  full_name='console_server_message.r7_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='console_server_message.r7_msg.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='console_server_message.r7_msg.count', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=185,
)


_R4_MSG = _descriptor.Descriptor(
  name='r4_msg',
  full_name='console_server_message.r4_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='console_server_message.r4_msg.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='console_server_message.r4_msg.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=224,
)


_R5_MSG = _descriptor.Descriptor(
  name='r5_msg',
  full_name='console_server_message.r5_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='console_server_message.r5_msg.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=248,
)


_R8_MSG = _descriptor.Descriptor(
  name='r8_msg',
  full_name='console_server_message.r8_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='console_server_message.r8_msg.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='console_server_message.r8_msg.error', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=287,
)


_FLAG = _descriptor.Descriptor(
  name='flag',
  full_name='console_server_message.flag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='console_server_message.flag.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='console_server_message.flag.flag', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['total_message'] = _TOTAL_MESSAGE
DESCRIPTOR.message_types_by_name['r7_msg'] = _R7_MSG
DESCRIPTOR.message_types_by_name['r4_msg'] = _R4_MSG
DESCRIPTOR.message_types_by_name['r5_msg'] = _R5_MSG
DESCRIPTOR.message_types_by_name['r8_msg'] = _R8_MSG
DESCRIPTOR.message_types_by_name['flag'] = _FLAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

total_message = _reflection.GeneratedProtocolMessageType('total_message', (_message.Message,), {
  'DESCRIPTOR' : _TOTAL_MESSAGE,
  '__module__' : 'c_s_message_pb2'
  # @@protoc_insertion_point(class_scope:console_server_message.total_message)
  })
_sym_db.RegisterMessage(total_message)

r7_msg = _reflection.GeneratedProtocolMessageType('r7_msg', (_message.Message,), {
  'DESCRIPTOR' : _R7_MSG,
  '__module__' : 'c_s_message_pb2'
  # @@protoc_insertion_point(class_scope:console_server_message.r7_msg)
  })
_sym_db.RegisterMessage(r7_msg)

r4_msg = _reflection.GeneratedProtocolMessageType('r4_msg', (_message.Message,), {
  'DESCRIPTOR' : _R4_MSG,
  '__module__' : 'c_s_message_pb2'
  # @@protoc_insertion_point(class_scope:console_server_message.r4_msg)
  })
_sym_db.RegisterMessage(r4_msg)

r5_msg = _reflection.GeneratedProtocolMessageType('r5_msg', (_message.Message,), {
  'DESCRIPTOR' : _R5_MSG,
  '__module__' : 'c_s_message_pb2'
  # @@protoc_insertion_point(class_scope:console_server_message.r5_msg)
  })
_sym_db.RegisterMessage(r5_msg)

r8_msg = _reflection.GeneratedProtocolMessageType('r8_msg', (_message.Message,), {
  'DESCRIPTOR' : _R8_MSG,
  '__module__' : 'c_s_message_pb2'
  # @@protoc_insertion_point(class_scope:console_server_message.r8_msg)
  })
_sym_db.RegisterMessage(r8_msg)

flag = _reflection.GeneratedProtocolMessageType('flag', (_message.Message,), {
  'DESCRIPTOR' : _FLAG,
  '__module__' : 'c_s_message_pb2'
  # @@protoc_insertion_point(class_scope:console_server_message.flag)
  })
_sym_db.RegisterMessage(flag)


# @@protoc_insertion_point(module_scope)
